In [1]:
import numpy as np

In [2]:
list=[20,27,9,12,31,17,5,50,39,35]

In [4]:
arr=np.array(list)
arr

array([20, 27,  9, 12, 31, 17,  5, 50, 39, 35])

In [5]:
arr*4

array([ 80, 108,  36,  48, 124,  68,  20, 200, 156, 140])

In [6]:
arr.mean()

np.float64(24.5)

In [8]:
np.median(arr)

np.float64(23.5)

In [9]:
arr.std()

np.float64(13.683932183404009)

In [11]:
np.argmin(arr)

np.int64(6)

In [12]:
np.argmax(arr)

np.int64(7)

In [13]:
np.min(arr)

np.int64(5)

In [15]:
np.max(arr) #these match the given indexes

np.int64(50)

In [22]:
narr=arr[arr>20]
narr

array([27, 31, 50, 39, 35])

In [23]:
matrix=[[5,12,17,9],[8,21,14,3],[6,13,19,11]]

In [26]:
matrixarr=np.array(matrix)
np.shape(matrixarr)

(3, 4)

In [31]:
matrixarr[:,2]

array([17, 14, 19])

In [33]:
matrixarr[1,:]

array([ 8, 21, 14,  3])

In [34]:
matrixarr*2

array([[10, 24, 34, 18],
       [16, 42, 28,  6],
       [12, 26, 38, 22]])

In [36]:
np.mean(matrixarr, axis=0) #mean of each column

array([ 6.33333333, 15.33333333, 16.66666667,  7.66666667])

In [45]:
np.mean(matrixarr)

np.float64(11.5)

In [46]:
np.max(matrixarr, axis=1)

array([17, 21, 19])

In [47]:
np.min(matrixarr, axis=0)

array([ 5, 12, 14,  3])

In [71]:
flatmatrix=matrixarr.flatten() #this condenses all the rows into one single row
flatmatrix

array([ 5, 12, 17,  9,  8, 21, 14,  3,  6, 13, 19, 11])

In [72]:
min_index=np.argmin(flatmatrix)
min_index

np.int64(7)

In [73]:
max_index=np.argmax(flatmatrix)
max_index

np.int64(5)

In [67]:
np.unravel_index(min_index,np.shape(matrix)) #tells you location of these in 
#the normal matrix 

(np.int64(1), np.int64(3))

In [74]:
np.unravel_index(max_index, np.shape(matrix))

(np.int64(1), np.int64(1))

In [78]:
matrix_greater15=matrixarr[matrixarr>15]
matrix_greater15

array([17, 21, 19])

In [83]:
np.sort(matrix_greater15) #it sorts the elements in each row from smallest to greatest

array([17, 19, 21])

In [84]:
#4 Prime Star Systems

In [290]:
starmags=np.array([[2,3,5],[14,6,8],[11,13,17],[7,10,13]])

In [287]:
#I create a function which checks if a number is prime
def prime_number(number): 
    if number<2:
        return False
    for i in range(2, int(number**0.5) +1): #plus 1 since range is start (included), stop (excluded). Int is also neeeded since range only accepts integers
        if number%i==0:
            return False #the function is stopped if a factor is found, otherwise, it returns True
    else:
        return True


In [277]:
#using np.vectorize is much more efficient, this works on each value in the arrray
#and i can create my own using this method as well.
#Then, using np.any, it'll sends back the rows which have at least one true value

In [278]:
prime_matrix=np.vectorize(prime_number)
valuesofprime=prime_matrix(starmags) #this saves which values are prime and which are not
valuesofprime

array([[ True,  True,  True],
       [False, False, False],
       [ True,  True,  True],
       [ True, False,  True]])

In [279]:
#finally, this function keeps the values of the rows which have at least one prime, or not
leftover=np.any(valuesofprime, axis=1) 
#this line then has the array starmags keep the rows where the boolean is true and their respective values.
prime_rows=starmags[leftover]
prime_rows 

array([[ 2,  3,  5],
       [11, 13, 17],
       [ 7, 10, 13]])

In [280]:
#5 Let's play checkers

In [281]:
#5.1

In [282]:
#5.2
zero8by8=np.zeros((8,8))  #shape gives me a tuple, with shape[0] being the amount of rows, and shape[2] being the amount of columns
for i in range(0,zero8by8.shape[0], 2): #so i want the rows, this targets the odd numbered rows
    for j in range(0, zero8by8.shape[1], 2):#this gives me the amount of values in each odd row
        zero8by8[i,j]=1
zero8by8
#Now i'll modify the even rows
for k in range(1,zero8by8.shape[0],2):
    for l in range(1, zero8by8.shape[0], 2):
        zero8by8[k,l]=1
zero8by8

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [283]:
def reverse_checkerboard(zero8by8):
    reversed_order=np.fliplr(zero8by8) #this function allows me to flip the rows from left to right!
    return reversed_order
print(reverse_checkerboard(zero8by8))

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [284]:
#6 The Expanding Universe

In [285]:
def expansion(word, num): #i can take the index, and to that, add spaces
    #for each letter, add num amount of spaces:
    length=len(word)
    new_word=""
    amnt_of_spaces=" " * num
    for p in range(0, length-1):
        new_word+= word[p]+ amnt_of_spaces
    new_word+=word[length-1] #these 2 lines ensure there are no spaces at the end
    return new_word

expansion("kittykat", 4)

'k    i    t    t    y    k    a    t'

In [286]:
#7 Second-Brightest Star

In [367]:
#2d array where each row is a star cluster, return array where second brightest returned
#from each row
#so, create a new array, loop though the shape, add the 2nd brightest to the array
def secondDimmest(assort):
    arr_2ndDimmest=[]
    sortedstars=np.sort(assort)#this arranges each value in each row from least to greatest
    place=sortedstars.shape[1]-2 #gives me the amount of indexes in a row, -2 for targeting the 2nd dimmest
    #Looping through each row
    for v in range(sortedstars.shape[0]):
        arr_2ndDimmest.append(sortedstars[v,place])
    return np.array(arr_2ndDimmest)

In [368]:
stars=np.random.randint(500,2000, (5,5))
stars

array([[ 984, 1959,  948, 1741,  923],
       [1725, 1514,  607,  791,  531],
       [1207, 1600, 1750,  642, 1544],
       [ 967, 1245,  861, 1226,  994],
       [1152, 1571,  894,  854, 1770]])

In [370]:
secondDimmest(stars)

array([1741, 1514, 1600, 1226, 1571])